#
# Copyright 2021-2022 Micro Focus or one of its affiliates.
#
# The only warranties for products and services of Micro Focus and its
# affiliates and licensors ("Micro Focus") are set forth in the express
# warranty statements accompanying such products and services. Nothing
# herein should be construed as constituting an additional warranty.
# Micro Focus shall not be liable for technical or editorial errors or
# omissions contained herein. The information contained herein is subject
# to change without notice.
#
# Contains Confidential Information. Except as specifically indicated
# otherwise, a valid license is required for possession, use or copying.
# Consistent with FAR 12.211 and 12.212, Commercial Computer Software,
# Computer Software Documentation, and Technical Data for Commercial
# Items are licensed to the U.S. Government under vendor's standard
# commercial license.
#

debug: false
server:
  port: 8080
  ssl:
    enabled: false
    key-store: ${SSL_KEYSTORE}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: ${SSL_KEYSTORE_TYPE}
    key-alias: ${SSL_CERT_ALIAS}
    key-password: ${SSL_PASSWORD}

https:
  port: 8443

spring:
  application:
    name: ThreadModelingSimplified
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:threatModel}
    username: ${SMARTCIPHER_DATABASE_USERNAME:postgres}
    password: ${SMARTCIPHER_DATABASE_PASSWORD:postgres}
    maximumPoolSize: ${SMARTCIPHER_DATABASE_MAXIMUM_POOL_SIZE:5}
    minimumIdle: 1
    hikari.schema: threatModel_schema
  flyway:
    locations:
      - classpath:/db/migration/postgresql
    createSchemas: true
    schemas: threatModel_schema
  sql:
    init:
      platform: postgres
  servlet:
    multipart:
      max-file-size: 100MB

logging:
  level:
    ROOT: ${CAF_LOG_LEVEL:WARN}
    com.microfocus.smartcipher: ${SMARTCIPHER_API_LOG_LEVEL:DEBUG}
    com.microfocus.caf.tag: ${CAF_API_SERVICE_LOG_LEVEL:${CAF_LOG_LEVEL:INFO}}
    org.springframework: ${CAF_SPRING_LOG_LEVEL:WARN}
