----------------------------------------------------------
-- Threat Modeling entity definitions
----------------------------------------------------------
CREATE TABLE IF NOT EXISTS components_type
(
	component_type_id integer NOT NULL,
	component_type_name character varying(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS components
(
	component_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	component_name character varying(80) NOT NULL,
	component_type_id integer NOT NULL,
	analysis_id integer NOT NULL,
	component character varying(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS questionnaire
(
	question_id integer NOT NULL,
	component_type_id integer NOT NULL,
	question character varying(1024) NOT NULL,
	yes_option character varying(256),
	no_option character varying(256),
	yes_nextSteps integer NOT NULL,
	no_nextSteps integer NOT NULL,
	threatID integer,
	helpText character varying(1024) NOT NULL,
	helpURL character varying(1024) NOT NULL,
	mitigationText character varying(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS app_metadata
(
	analysis_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	userName character varying(256),
	product character varying(256),
	version character varying(256),
	status character varying(256)
);

CREATE TABLE IF NOT EXISTS responses
(
	analysis_id integer NOT NULL,
	component_id character varying(256) NOT NULL,
	question_id integer NOT NULL,
	response_option character varying(256),
	is_threat boolean NOT NULL,
	threat_id integer NOT NULL,
	dread character varying(10),
	mitigation character varying(1024) NOT NULL
);

--can have a separate table for threats
CREATE TABLE IF NOT EXISTS threats
(
	threat_id integer NOT NULL,
	threat character varying(256)
);

